### ISSUE TITLE
Error: Downloaded File xyz.jkl is corrupt.

### ISSUE THREAD

**Issue by JesterNovoN** [yasirkula/SimplePatchTool#1]
Greetings,

Thanks for the library it's a relief to be able to not reinvent the wheel on this.

I'm having an issue once all the system is up and running.

Everytime the application tries to update it locks always after the first file claiming it's corrupted.
Did you ever have any similiar problems previously or am i the only one?
And do you have any idea how to solve this?

I'm open for brainstorming.

![problemscreen](https://user-images.githubusercontent.com/5576511/49793474-93d36980-fd35-11e8-8e98-60cffed6c430.png)

**Comment by FreezerJohn** [comment]
I once came across this when I accidentally uploaded the files per ftp in ASCII mode. Therefore the checksum was different and it rightly reported the file as corrupt.

**Comment by JesterNovoN** [comment]
I am pretty sure i went for binary mode.
I'll double-check it. Thanks.

**Comment by JesterNovoN** [comment]
Double checked.
The files are transferring through binary mode.
The problem still applies.
Thanks anyway.

EDIT: Tried to make it work from local as well.
No luck whatsoever.
Could it be the creation of the patcher itself is corrupting some files?

**Comment by yasirkula** [comment]
What does the contents of _globalgamemanagers_ inside `%APPDATA%/../Local/SimplePatchToolDls/` look like? Maybe the downloaded file is actually a 403 HTML page stating that the file is not public or etc.

**Comment by JesterNovoN** [comment]
It's just an empty 0 bytes file.
I'm trying locally with "file:///" now.

**Comment by yasirkula** [comment]
Does entering the download url of the file to your web browser indeed download the file or does it return an error message?

**Comment by JesterNovoN** [comment]
Tried it now. Downloaded the file just fine.

**Comment by yasirkula** [comment]
Can you send your VersionInfo.info to me so that I can check it out? Feel free to send an email: yasirkula@gmail.com

**Comment by JesterNovoN** [comment]
Nevermind i'm an idiot.
The version i had down was not in line with the github version. 
After updating everything worked fine.
Thanks again for the port and for supporting my dumb ass.
