### ISSUE TITLE
Questions not issues

### ISSUE THREAD

**Issue by MScottAdams** [yasirkula/SimplePatchTool#11]
Wonderful app!

Sorry if this is the wrong spot for questions. Is there a community forum somewhere?

I am using the Unity plugin version.

Questions:
1) Does the generate patch need the baseline and all previous versions of the builds in the Versions directory to work? If not what is the minimum it needs? 

2) Can new versions be labeled differently than 1.1? I.e. first version is 1.0 next version is 50.1g Would that work?

**Comment by yasirkula** [comment]
Hi,

1. Only the newest version is sufficient. However, if you are planning to create incremental patches, then the previous version is also needed.
2. Letters aren't supported and the version number must be greater than the previous version number. So, 1.0->50.1 is fine but 1.0->50.1g or 1.0->0.50.1 isn't.

P.S. The Unity version has its own [repository](https://github.com/yasirkula/UnitySimplePatchTool) and a [forum thread](https://forum.unity.com/threads/simplepatchtool-open-source-patching-solution-for-standalone-platforms.542465/) 😸
