### ISSUE TITLE
No suitable patch method found

### ISSUE THREAD

**Issue by tindolt-zz** [yasirkula/SimplePatchTool#2]
I am at a loss of what is wrong. I built LauncherWindow.cs and it wont update (I have all the versions upploaded to the server just fine ((also it will repair but not update)))

**Comment by yasirkula** [comment]
Are you calling `UseRepairPatch(false)` in your update code? Which patch(es) did you generate: repair patch, incremental patch and/or installer patch? Do they all have a DownloadURL in VersionInfo (or did you use a BaseDownloadURL instead)? Do all patches also have non-zero/nonempty MD5 hashes and Filesizes in VersionInfo?

**Comment by tindolt-zz** [comment]
Where would I call UseRepairPatch? and I am having troubles with incremental patch and install patch, I generated incremental and installer patchs, download url is directed at the proper location (basdownloadurl is not being used as my server is picky and doesnt like it for some reason) and yes my version info has md5 hashs and filesizes on both incre and installer patchs

**Comment by tindolt-zz** [comment]
also where is the update code that you are talking about? 
sorry I have like 200 things that call the Update function in my main project and then there are like self patcherwin and launcherwin in visual studio, screenshot of where your talking about would be nice :)
Also just going to use here and not unity forums XD (I generated Installer.patch and Incremental.patch as this is going from version 0.5 -> 0.6 of main project and SPPatcher has selfpatcher.exe and selfpatcher dll in it as well as I have the .dll for launcher in main directory as well (also in version info I have ignored game patch like the tutorial said, was I not supposed to do that?)

**Comment by yasirkula** [comment]
It all looks fine. I meant the SimplePatchTool object's UseRepairPatch function; if you are not calling it at all, then there should be no problem.

It would really help if I could see your VersionInfo. If you modified the launcher's source code, I would like to take a look at that, as well. Can you please send these to me via email (yasirkula@gmail.com)?

**Comment by tindolt-zz** [comment]
Solution to problem for any having it. Launcher download urls were incorrect I think changing them fixed it.
