### ISSUE TITLE
Problems with InstallerPatch and Incremental Patch

### ISSUE THREAD

**Issue by Dirkulez** [yasirkula/SimplePatchTool#3]
Hi there! 

I am just testing SimplePatchTool since I need such functionality for a project. Unfortunately I am faced with some problems concerning InstallerPatches and IncrementalPatches. RepairPatches seem to work without any problems. 

Downloading and Decompressing works fine but copying the files fails. Seems the InstallerPatchApplier / IncrementalPatchApplier does not use the correct path. Or from an other point of view the Patch has not the expected structure or rather is not extracted to the expected path.
For example the Installer Patch has a structure like Installer.patch\Installer\<project name>\Versions\<version>\ (similar to the project sructure) and is extracted to %APPDATA\..\local\SimplePatchToolDls\<project name>\InstallerPatch\<project folder>\Versions\<version>\
When the InstallerPatchApplier tries to copy the files it expects the files at %APPDATA\..\local\SimplePatchToolDls\<project name>\InstallerPatch\

Similar behavior with the IncrementalPatch ... with little different structure in the patch file and different expected path in the PatchApplier.

Am I doing anything wrong or could there a problem with the SimplePatchTool? 

Best regards
Dirk

**Comment by yasirkula** [comment]
Please let me know if [this fix](https://forum.unity.com/threads/simplepatchtool-open-source-patching-solution-for-standalone-platforms.542465/page-4#post-4719608) resolves the issue.

**Comment by Dirkulez** [comment]
Looks good. Now the patches seem to have the correct structure regardless of the -projectRoot parameter.

Thanks for the good support!!

**Comment by yasirkula** [comment]
Fixed: https://github.com/yasirkula/SimplePatchTool/commit/b4ca15f5cca7fdf79893ff93b226cda74f894d45
