### ISSUE TITLE
force update

### ISSUE THREAD

**Issue by liuyichuan** [yasirkula/SimplePatchTool#5]
Any chance to create a force update feature(must update before user enter the application)?

**Comment by yasirkula** [comment]
When the app launches, you can disable the Play button and call `SimplePatchTool.CheckForUpdates(false)`. After the process is completed, you can check the `SimplePatchTool.Result` value:

**PatchResult.AlreadyUpToDate:** enable the Play button
**PatchResult.Success:** there is an update, either enable the Update button or automatically start updating the app via `SimplePatchTool.Run`
**PatchResult.Failed:** there was an error while checking for updates, I'd recommend you to try checking for updates again
