### ISSUE TITLE
Obsolete files problem

### ISSUE THREAD

**Issue by liuyichuan** [yasirkula/SimplePatchTool#6]
What changes will mark a file as an obsolete file?
And what's the result if I don't check the obsolete files after the update?   

If the user generates some database files inside the app folder, they will be told obsolete file exist in the next update. But I can't use ignore feature because I need these directories to keep my app run when they make a new installation use install.patch.

`
            if (!CheckLocalFilesUpToDate(false, comms.SelfPatching))
            {
                comms.Log(Localization.Get(StringId.SomeFilesAreStillNotUpToDate));

                if (canRepairPatch)
                {
                    if (!PatchUsingRepairPatch())
                        return PatchResult.Failed;
                }
                else
                {
                    FailReason = PatchFailReason.FilesAreNotUpToDateAfterPatch;
                    FailDetails = Localization.Get(StringId.E_FilesAreNotUpToDateAfterPatch);

                    return PatchResult.Failed;
                }
            }`

After commenting these code in SimplePatchTools.cs  I work fine.

**Comment by yasirkula** [comment]
If you are trying to prevent a file/folder from getting deleted during a patch, then adding those files to the `IgnoredPaths` list in VersionInfo.info is the way to go. SimplePatchTool doesn't delete a file/folder if **a)** it is included in the patch or **b)** it is included in IgnoredPaths.

**Comment by liuyichuan** [comment]
Yes, I understand the logic. But when I update the MainApplication, the program didn't delete the files that not included in the patch and give me the obsolete file error.

**Comment by yasirkula** [comment]
I'd like to pinpoint the issue. Is it about generated database files being deleted in a patch or some leftover files (e.g. file_no_longer_in_use.txt) not getting deleted in a patch? Which IgnoredPaths do you have in your main application's VersionInfo?

**Comment by liuyichuan** [comment]
Actually, the thing is the update engine detected the obsolete files then did nothing, just throw the error.
I figure it out after reading the source code. 
I find the logic is when the engine detected some file's size or md5 is not match with VersionInfo, it will be marked as an obsolete file. So the engine will find a solution to replace these files. 
What I faced is the engine couldn't find out a solution to fix the obsolete files and just gives me the obsolete error on the UI panel. After I generate a repair patch, it will download files from the server then replace the obsolete files and works fine.
Thanks for the patience and this is a great project.
