### ISSUE TITLE
<html xmlns=''> was not expected.

### ISSUE THREAD

**Issue by gaetandezeiraud** [yasirkula/SimplePatchTool#8]
Hi, 
I have a problem with the VersionInfo.info. When I start an auto-update WPF application. I have this error: 

```
...Checking for updates...
System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVersionInfo.Read7_VersionInfo()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at SimplePatchToolCore.PatchUtils.DeserializeXMLToVersionInfo(String xmlContent)
   at SimplePatchToolCore.SimplePatchTool.FetchVersionInfo()
ERROR: version info is invalid
```

I think it's a problem with nginx. The file is here [http://play.exoway.net/VersionInfo.info](http://play.exoway.net/VersionInfo.info). Any idea?

**Comment by gaetandezeiraud** [comment]
Here my nginx configuration: 

```
server {
        server_name play.exoway.net;
        listen 80;
        location / {
            root /var/www/exoway-play;
            autoindex on;
            types {
                text/xml info;
            }
         }
    }
```

**Comment by gaetandezeiraud** [comment]
And if I remove autoindex. I have this simple error `...Checking for updates...
ERROR: could not download version info from server`.

**Comment by yasirkula** [comment]
Did you resolve the issue?

**Comment by gaetandezeiraud** [comment]
Yes sorry. I forgot the `VersionInfo.info` at the end of VERSION_INFO_URL.
Thanks.

**Comment by Brouilles** [comment]
I have a new problem `ERROR: self patcher does not exist`. I have the `SelfPatcher.exe` and `SelfPatcherCore.dll` in **SelfPatcher** directory. But do not worry, probably a misunderstood step by me.

**Comment by yasirkula** [comment]
Can you verify that the self patcher files are copied to the SPPatcher directory of your build in Versions folder automatically?
